-- ============================================================
-- Tablas de presupuestos (budgets)
-- Separadas de orders para no afectar ventas ni stock hasta
-- su conversión explicita a una orden.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.budgets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  admin_client_id uuid REFERENCES public.admin_clients(id) ON DELETE SET NULL,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'sent', 'accepted', 'rejected', 'expired', 'converted')),
  notes text,
  validity_days integer NOT NULL DEFAULT 15,
  valid_until date,
  subtotal numeric NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL DEFAULT 0,
  converted_order_id bigint REFERENCES public.orders(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.budget_items (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  budget_id bigint NOT NULL REFERENCES public.budgets(id) ON DELETE CASCADE,
  variant_id uuid NOT NULL REFERENCES public.variants(id),
  quantity integer NOT NULL,
  price numeric NOT NULL,
  product_snapshot jsonb NOT NULL
);

-- ============================================================
-- Ampliar el canal de venta de orders para la conversión
-- ============================================================
ALTER TABLE public.orders DROP CONSTRAINT IF EXISTS orders_sale_channel_check;

ALTER TABLE public.orders
  ADD CONSTRAINT orders_sale_channel_check
  CHECK (sale_channel IN ('online', 'pos', 'presupuesto'));

-- ============================================================
-- RLS: solo admins pueden gestionar presupuestos
-- ============================================================
ALTER TABLE public.budgets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.budget_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admin can manage budgets"
  ON public.budgets
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_id = auth.uid() AND role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_id = auth.uid() AND role = 'admin'
    )
  );

CREATE POLICY "Admin can manage budget_items"
  ON public.budget_items
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_id = auth.uid() AND role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.user_roles
      WHERE user_id = auth.uid() AND role = 'admin'
    )
  );

-- ============================================================
-- Indices
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_budgets_admin_client
  ON public.budgets (admin_client_id);

CREATE INDEX IF NOT EXISTS idx_budgets_status
  ON public.budgets (status);

CREATE INDEX IF NOT EXISTS idx_budgets_created_at
  ON public.budgets (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_budget_items_budget
  ON public.budget_items (budget_id);
